name = "Parametric"
license = "MIT"
licenselink = "https://github.com/wamuir/parametric/blob/master/LICENSE"
description = "Parametric is a minimal and clean personal theme for Hugo."
homepage = "https://wamuir.github.io/parametric/"
tags = ["academic", "cv", "personal", "portfolio", "resume"]
features = []
min_version = "0.41.0"

[author]
  name = "William Muir"
  homepage = "https://wamuir.github.io"
